version: '3' 
services:

  mysql:
    build: ./mysql/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hazlocondatos_sql
    ports:
      - '3310:3306'
    volumes: 
      - ./mysqldata:/mysql/data
    env_file: 
      - ./mysql/variables.env
